[theme]
backgroundColor="#f4f5f7"  # A light, soft gray for the primary background
secondaryBackgroundColor="#4c6ef5"  # A rich, modern blue for accents
textColor="#2d3436"  # A dark gray for better text readability
font="serif"  # Keeps the font elegant and professional


